version: '3'
services:
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: bookmarks
      MARIADB_ROOT_PASSWORD: password
    ports:
      - 3306:3306
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookmarks
    ports:
      - 5432:5432
