name: 'Ensure test passes'
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  tests:
    name: Tests with NodeJS v${{ matrix.node }} with ${{ matrix.db.id }}
    runs-on: ubuntu-latest
    env:
      PORT: 3000
      NODE_ENV: test
      JWT_SECRET: b01f741e726e4117
      APP_SECRET: b683f9abb8e7485c
      LOG_TARGET: none
    strategy:
      matrix:
        db:
          - id: postgres
            services:
              db:
                image: postgres
                env:
                  POSTGRES_PASSWORD: postgres
                ports:
                  - 54320:5432
                options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=5
            env:
              DB_TYPE: postgres
              DB_HOST: localhost
              DB_PORT: 54320
              DB_USER: postgres
              DB_PASS: postgres
              DB_NAME: postgres
          - id: mysql
            services:
              db:
                image: mariadb
                env:
                  MARIADB_USER: user
                  MARIADB_PASSWORD: password
                  MARIADB_DATABASE: bookmarks
                  MARIADB_ROOT_PASSWORD: root
                ports:
                  - 33060:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
            env:
              DB_TYPE: mariadb
              DB_HOST: localhost
              DB_PORT: 33060
              DB_USER: user
              DB_PASS: password
              DB_NAME: bookmarks
          - id: sqlite
            env:
              DB_TYPE: sqlite
              DB_NAME: db/test.db
            services: {}
        node: [20]
    services: ${{ matrix.db.services }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          NODE_ENV: development

      - name: Linting
        run: npm run lint --max-warnings=0
        env:
          NODE_ENV: development

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Test
        run: npm test
        env: ${{ matrix.db.env }}
