name: 'Build docker image'
on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    name: Tests with NodeJS v${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Linting
        run: npm run lint --max-warnings=0

      - name: Build
        run: npm run build

      - name: Test
        run: npm run build:test

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          labels: |
            maintainer=kelgors
          images: |
            name=${{secrets.DOCKER_IMAGE}}
          tags: |
            type=semver,pattern={{version}}-slim
            type=semver,pattern={{major}}.{{minor}}-slim
            type=semver,pattern={{major}}-slim
            type=raw,value=slim

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
